packages:
  - 'packages/*'
  - 'examples/*'

strictDepBuilds: true
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

blockExoticSubdeps: true

minimumReleaseAge: 1200
minimumReleaseAgeExclude: []

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200
trustPolicyExclude:
  - ts-api-utils@2.3.0
